# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 05:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialshield', '0002_remove_user_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dangerlevel',
            old_name='user_name',
            new_name='screen_name',
        ),
    ]
