# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialshield', '0003_auto_20161002_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dangerlevel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='dangerlevel',
            name='screen_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='oauth_token',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
