# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialshield', '0004_auto_20161005_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='dangerlevel',
            name='anger_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dangerlevel',
            name='disgust_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dangerlevel',
            name='sadness_level',
            field=models.IntegerField(default=0),
        ),
    ]
